catalog/urls.py
from django.urls import path
from .views import index, LiteraryGenreListView, BookListView, AuthorListView, BookDetailView, test_session_view, AuthorDetailView, author_create

# https://docs.djangoproject.com/en/5.0/topics/http/urls/

urlpatterns = [
    path("", index, name="index"),
    path("literary-genres/", LiteraryGenreListView.as_view(), name="literary-genre-list"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/create/", author_create, name="author-create"),
    path("test-sessions/", test_session_view, name="test-session"),
]

app_name = "catalog"

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

catalog/models.py
import datetime

from django.db import models
from django.urls import reverse


class LiteraryGenre(models.Model):
    genre = models.CharField(
        max_length=16,
        help_text="Enter a literary genre (e.g. Science Fiction, French Poetry etc.)",
        unique=True,
    )

    def __str__(self):
        return f"{self.id} - {self.genre}"


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)
    description = models.TextField(default="No description available")

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class Book(models.Model):
    ItemType = (
        ("BOOK", "Book"),
        ("MAGAZINE", "Magazine"),
        ("NEWSPAPER", "Newspaper"),
        ("JOURNAL", "Journal"),
        ("BOARDGAME", "Boardgame"),
        ("OTHER", "Other"),
    )
    title = models.CharField(max_length=200)
    description = models.TextField(default="No description available")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    added_on = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=10, choices=ItemType, default="BOOK")
    genre = models.ForeignKey(
        LiteraryGenre, on_delete=models.CASCADE, related_name="books", null=True
    )
    authors = models.ManyToManyField(Author, related_name="books")

    def __str__(self):
        return (
            f"id: {self.id}, {self.title}, price={self.price}\n"
            f"{self.description}\n"
            f"added: {self.added_on}"
        )

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms

from catalog.models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"  # or ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'description']

catalog/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .forms import AuthorForm
from .models import Book, Author, LiteraryGenre


def test_session_view(request: HttpRequest) -> HttpResponse:
    request.session["book"] = "Test session book"
    return HttpResponse(
        "<h1>Test session view</h1>"
        f"<h4>Session data: {request.session['book']}</h4>"
    )


def index(request: HttpRequest) -> HttpResponse:
    num_book = Book.objects.count()
    num_author = Author.objects.count()
    num_genre = LiteraryGenre.objects.count()
    time_and_date = datetime.now()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    return render(
        request,
        "catalog/index.html",
        context={
            "num_books": num_book,
            "num_authors": num_author,
            "num_genres": num_genre,
            "datetime": time_and_date,
            "num_visits": num_visits + 1,
        },
    )


# https://docs.djangoproject.com/en/5.0/topics/class-based-views/generic-display/
class LiteraryGenreListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryGenre
    context_object_name = "literary_genre_list"  # показати як формуються імена за замовченням
    template_name = "catalog/literary_genre_list.html"  # показати як формуються шаблони за замовченням


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.select_related("genre")
    paginate_by = 3


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


# def book_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
#     try:
#         book = Book.objects.get(pk=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")
#     return render(request, "catalog/book_detail.html", context={"book": book})


def author_create(request: HttpRequest) -> HttpResponse:
    context = {}
    form = AuthorForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("catalog:author-list"))
    context["form"] = form
    return render(request, "catalog/author_form.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block title %}
    <title>Library</title>
  {% endblock %}
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}

      {% endblock %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
    </div>
</body>
</html>

templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Author:</h1>
  <div class="m-lg-3">
    {{ author.first_name }} {{ author.last_name }}
    <hr>
    {% if author.date_of_birth %}
      {{ author.date_of_birth|date:"F j, Y" }} -
    {% else %}
      Unknown -
    {% endif %}
    {% if author.date_of_death %}
      {{ author.date_of_death|date:"F j, Y" }}
    {% else %}
      Present
    {% endif %}
  </div>
{% endblock %}

templates/catalog/author_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Author</h1>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors:</h1>
  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{% url 'catalog:author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No authors are available.</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Genre: </strong>{{ book.genre }}</p>
  <hr>
  <div class="m-lg-3">
    <h3>Authors:</h3>
    {% if book.authors.all %}
      <ul>
        {% for author in book.authors.all %}
          <li>
            <a href="{% url 'catalog:author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
          </li>

        {% endfor %}
      </ul>
    {% else %}
      <p>No authors!</p>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Book list:</h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.genre }})</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No books are available.</p>
  {% endif %}

{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block title %}
  <title>Library: home page</title>
{% endblock %}

{% block content %}
  <h1>Welcome to the Library!</h1>
  <hr>
  <p>current data and time: {{ datetime }}</p>
  <br>
  <h2>Library contains:</h2>
  <ul>
    <li>{{ num_books }} books are available.</li>
    <li>{{ num_authors }} authors are available.</li>
    <li>{{ num_genres }} genres are available.</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}

templates/catalog/literary_genre_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Literary genre list</h1>
  {% if literary_genre_list %}
    <ul>
      {% for literary_genre in literary_genre_list %}
        <li>{{ literary_genre.genre }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No literary genres are available.</p>
  {% endif %}
{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
    {% endif %}
    <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li><strong>User: {{ user.username }}</strong></li>
    <li>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
      </form>
    </li>
  {% else %}
    <li><a href="{% url 'login' %}">Login</a></li>
  {% endif %}
  <br>
  <li><a href="{% url 'catalog:index' %}">Home</a></li>
  <li><a href="{% url 'catalog:book-list' %}">All books</a></li>
  <li><a href="{% url 'catalog:author-list' %}">All authors</a></li>
  <li><a href="{% url 'catalog:literary-genre-list' %}">All literary genre</a></li>
</ul>